### ISSUE TITLE
BetterBlingEdit v1.0 roadmap

### ISSUE THREAD

**Issue by MMK21Hub** [MMK21Hub/BlingEdit#1]
**Currently waiting for** MC 1.16 to enter the pre-release stage. This should (hopefully) mean I don't have to rewrite everything when Mojang makes a technical change.

- [ ] Rewrite version detection. (#2)

- [ ] Line break function (like `blingedit:clear` but for one line).

- [x] Remove 'Check for Updates' link.

- [ ] Options rewrite, and third page.

- [ ] Help book rewrite.

- [ ] 'Logged in as' notice?

- [ ] Make it so that you can fill air.

- [ ] Semifix for [this bug](https://www.reddit.com/r/BlingEdit/comments/giuwst/big_bug_with_not_full_block/)?

- [ ] https://www.reddit.com/r/BlingEdit/comments/gizs50/big_bug_with_to_long_selection/?utm_medium=android_app&utm_source=share

- [ ] Bugfixes for any bugs I come across.
